language: cpp
sudo: enabled
dist: trusty
compiler:
  - g++
os:
  - linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake
      - lcov
      - g++
      - libeigen3-dev
      - libgtest-dev
      - tree

before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0; mkdir build; cd build
  - cmake -DBUILD_SHARED_LIBS=ON ../
  - make; sudo make install
  - cd ../../

script:
  - pwd
  - mkdir build; cd build
  - cmake ../

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - pwd

