language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
  - sudo apt-get install -y libeigen3-dev libgtest0 libgtest-dev
  - ls /usr/include/gtest
  - ls /usr/lib/

script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ../
  # - ctest